            - name: Setup Odin
  # You may pin to the exact commit or the version.
  # uses: laytan/setup-odin@447aa179880a3f4e94011007c65cb9efdb6dd6a0
  uses: laytan/setup-odin@v2.11.0
  with:
    # GitHub token to make requests from, must be set to download releases
    token: # optional
    # The Odin branch to setup, supports tag names and branch names
    branch: # default is master
    # The Odin release to setup, if set, this will try to download a tagged GitHub release with this name instead of pulling/compiling, `latest` can be used to setup the latest release
    release: # optional, default is latest
    # Which version of LLVM to install
    llvm-version: # default is 18
    # Type of Odin build, supports "debug", "release" or "release_native"
    build-type: # default is debug
    # The repository to pull Odin from
    repository: # default is https://github.com/odin-lang/Odin
    # Enables caching the compiler binary, NOTE: this is probably slower than redownloading it everytime and is thus deprectated.
    cache: # optional, default is false
          
